<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_TestFunctionBlock" Id="{b0a54a4d-cef1-4465-aa75-b643b5e47f92}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TestFunctionBlock
VAR
	nCounter : LINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[nCounter := nCounter + 1;]]></ST>
    </Implementation>
    <LineIds Name="FB_TestFunctionBlock">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>