<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{802e6176-3be3-4153-b01c-d723f6ad006d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbO5D100 : Identical_Library.FB_O5D100;
	fbO5D100_2 : Identical_Library.FB_O5D100;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbO5D100();
fbO5D100_2();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>